### ISSUE TITLE
ascii hosting provider isn't mobile friendly

### ISSUE THREAD

**Issue by rileytg** [knq/usql#1]
i know this isn't ur problem at all, this is just the 5th really cool repo i've seen recently using this ascii video provider instead of a gif (or something like youtube). and it really just sucks on mobile. had to say something.

**Comment by rileytg** [comment]
closing. off topic.

**Comment by kenshaw** [comment]
Thanks for the input -- what would you recommend? I think I gif would be much heavier on bandwidth. YouTube is definitely a possibility. It's just hard to beat the ease by which asciinema makes capturing console output.
