### ISSUE TITLE
Does usql support authenticating via domain to MS Sql?

### ISSUE THREAD

**Issue by sorakiu** [knq/usql#10]
One thing I hate is trying to SSMS to come up correctly when I'm connecting with Domain Auth to a domain that I don't have a trust with.  Does Usql have the capability to auth via domain to a domain with no trust?

**Comment by kenshaw** [comment]
I'm not really sure, and I don't have a Windows domain set up here to try with. The underlying driver used is: https://github.com/denisenkom/go-mssqldb

From the documentation for the mssql driver:
```
"user id" - enter the SQL Server Authentication user id or the Windows Authentication user id in the DOMAIN\User format. On Windows, if user id is empty or missing Single-Sign-On is used.
```

If that's the case, then I imagine writing the user in the URL would just be a matter of URL escaping the \. Not sure if the SSO referred to here means/implies local Windows domain SSO

**Comment by kenshaw** [comment]
BTW -- I would appreciate if you could try out the various driver parameters with your Windows domain and `usql`, and provide feedback here on whether or not there is a way to get it to connect to a windows domain. 

Probably the fastest way to test a bunch of parameters would be to use `\c <url>` to connect, execute a simple `SELECT` (to see if it works) then use the up arrow on the command line to modify the connect string if it did not. You could, in that fashion, rapidly try different combinations of the various driver parameters! If you do this, please report back your findings! I'd love to document the connection string for a Windows domain would be.

ie:
```sh
$ usql
Type "help" for help.

(not connected)=> \c ms://user:pass@localhost/?param1=value
ms:user@localhost=> select * from users;
error: mssql: Login failed
ms:user@localhost=> <PUSH THE UP ARROW>\c ms://user:pass@localhost?param1=value&param2=val2

```

**Comment by sorakiu** [comment]
I will give it a try tomorrow at work - I lost track of this and will
follow-up!

**Comment by sorakiu** [comment]
I downloaded the precompiled version b/c i'm on windows and I spent a hour trying to figure out how to get go working on windows and failed.  :-( 

I was getting a lot of control characters when i tried to type.  I did domain\username as you suggested and got the following error (below) - any ideas on how to get this going on windows?  i have an ubu VM at work that i could try if that would be easier

`C:\scratch\usql>usql
Type "help" for help.

(not connected)=> \c ms://***:***@localhost/←[J←[2K
ms:***\***@localhost=> select * from users;←[J←[2K
error: mssql: InitialBytes InitializeSecurityContext failed 8009030c`

**Comment by kenshaw** [comment]
Sorry about that. Yes, I had pushed the first release even though I knew about the problems. I just pushed a fix now for it. Try it and let me know if the terminal issues are fixed for you.

**Comment by kenshaw** [comment]
Any luck testing with a Windows Domain?

**Comment by sorakiu** [comment]
I got it working!!

So if my values were:

- username: ACME\wiley
- password: bar@
- hostname: server

I would run:

```
ms:server/DEV_CTMLS_MATRIX_DATA-> /c ms://ACME/wiley:bar{@}@server/TEST_DATABASE
ms:server/DEV_CTMLS_MATRIX_DATA-> select * from sys.databases;
error: Login error: mssql: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.
```

So I think this is the explanation right here - the only way this could work is if I either use SQL server authentication or impersonate like I've been doing with SSMS.

So this works!

```
runas /user:ACME\wiley /netonly usql.exe

 (not connected)=> \c ms://server/database
```

I had some issues with the text formatting in the output, but I was definitely getting data.

The window has the title "usql.exe (running as ACME\wiley)"

**Comment by kenshaw** [comment]
Ok, cool! What were the issues with the output?

**Comment by bruth** [comment]
I am running into this problem as well. It appears the core problem is that the URL userinfo doesn't allow backslashes?

```
% usql "mssql://mydomain\\username@localhost:1433/mydb"
error: parse mssql://mydomain\username@localhost:1433/mydb: net/url: invalid userinfo
```

**Comment by kenshaw** [comment]
`usql` uses Go's standard `net/url.Parse` func. As such, you likely need to URL encode the backslash (`%5c`):

```sh
% usql 'mssql://domain%5cuser:password@host:port/database'
```

If you look at the `README.md`, there's also an example using the `runas` command:

```sh
% $ runas /user:ACME\wiley /netonly "usql mssql://host/dbname/"
```

**Comment by bruth** [comment]
Bah, that has bitten me before. This behavior had [changed](https://github.com/golang/go/issues/23392) and I forgot that I need to escape it before passing it. Sorry about that and thank you.

A quick side question.. I maintain https://github.com/chop-dbhi/sql-agent which provides an HTTP frontend for querying a database. After coming across this project, I would love to leverage the core library.. basically all the driver normalization and standard interfaces. Do you have a suggestion on how to integrate this work as a package? I suppose I can just look at the `main.go` to see how it is setup and queries are invoked? Obviously all the shell-related things are not applicable for my use case.

**Comment by kenshaw** [comment]
`usql` doesn't really add much to the standard Go library -- it just simply uses all the various published database drivers (that I'm aware of), and wraps it up in a simple package that reads input from the command line. You're more than welcomed (encouraged, even!) to use the underlying packages. Things have been kept extremely modular, but `usql`'s design is really around a standard "input loop" model. I'm not sure what use it would be in a HTML based app -- it would seem more simple / straight forward to simply send a SQL query straight to the respective database. The real useful package for that would be `dburl` that builds the appropriate DSNs for the database drivers. I can't imagine the code in `usql` for, eg, the syntax highlighting would be useful outside of a command line context. Anyway, if you do end up using it, let me know -- cheers!

**Comment by bruth** [comment]
Thanks for the info.

> I'm not sure what use it would be in a HTML based app

The intent of sql-agent is to be a stateless backend service that other services can send connection info and queries to that will execute the query on behalf of the service over HTTP.

Yes `dburl` is likely what I will use. Thanks very much!
