### ISSUE TITLE
Support to open last command in $EDITOR

### ISSUE THREAD

**Issue by chischaschos** [knq/usql#11]
Hi I'm starting to use `usql` I love it. Thank you.

It would be great if you could open the last entered command in an editor, save the command and execute it. Will look into it later this week.

**Comment by kenshaw** [comment]
Yes. I'm in the middle of writing a real line parser. With it, will come support for things like EDITOR, PAGER, and all the other Unix style stuff, as well as support for about 80% of what `psql` can do out of the box. Bear with me though, as this project is less than 1 week old, was originally only cobbled together to support [`xo`](https://github.com/knq/xo) and I didn't anticipate it getting as much attention as it has. That said, given that it's likely less than 1000 lines of code to support "everything" that `psql` does (thanks to the power of Go!), and it ends up having a single, approximately 3 megabyte binary for every single platform (OSX, Windows, Linux, etc.) that works correctly and consistently with "every" major SQL database it really makes a lot of sense to flesh it out and promote it from 'toy' to 'real tool'.

**Comment by kenshaw** [comment]
For reference, this is how I am creating databases using `usql` on Linux with MSSQL:

```sh
usql $DB -c "exec sp_configure 'contained database authentication', 1;"
usql $DB -c "reconfigure;"
usql $DB -c "drop login $NAME;"
usql $DB -c "drop database $NAME;"
usql $DB -c "create database $NAME containment=partial;"

usql $DB/$NAME -c "create login $NAME with password='$NAME', check_policy=off, default_database=$NAME;"
usql $DB/$NAME -c "create user $NAME for login $NAME with default_schema=$NAME;"
usql $DB/$NAME -c "create schema $NAME authorization $NAME;"
usql $DB/$NAME -c "exec sp_addrolemember 'db_owner', '$NAME';"
```

The above is the relevant parts from `contrib/mscreate.sh` script in the [github.com/knq/xo](https://github.com/knq/xo) project.

**Comment by kenshaw** [comment]
Soon. Very, very, soon. Please test out the latest version of `usql`, to test the pseudo-non-naive "parser".

**Comment by kenshaw** [comment]
`$EDITOR` is now along with the \e or \edit command. It works the same as `psql`:
```sh
$ ./usql pg://booktest:booktest@localhost/
Type "help" for help.

pg:booktest@localhost=> select * from authors
pg:booktest@localhost-> where name like '%'
pg:booktest@localhost-> ;
  author_id |      name       
+-----------+----------------+
          1 | Unknown Master  
(1 rows)

pg:booktest@localhost=> \p
select * from authors
where name like '%'
;
pg:booktest@localhost=> \e
pg:booktest@localhost-> \p
select * from authors a 
inner join books b on a.author_id=b.author_id
limit 1
pg:booktest@localhost-> \g
  author_id |      name      | book_id | author_id | isbn | booktype |     title     | year |            available             | tags  
+-----------+----------------+---------+-----------+------+----------+---------------+------+----------------------------------+------+
          1 | Unknown Master |       1 |         1 |    1 | FICTION  | my book title | 2016 | 2017-03-16T18:32:54.575785+07:00 | {}    
(1 rows)

pg:booktest@localhost=> 
```
