### ISSUE TITLE
Brew formula

### ISSUE THREAD

**Issue by ZloeSabo** [knq/usql#12]
Hello!
Thanks for the tool. Are you planning to create homebrew formula to install it on mac?
If not really, would you mind if I add it mysqlf to my [nettools repo](https://github.com/ZloeSabo/homebrew-nettools) ?

**Comment by kenshaw** [comment]
I'll try to make it available to all the various system repositories. I'm not familiar with what's needed for publishing a homebrew formula, but I'll look into it.

**Comment by majkinetor** [comment]
I plan to maintain Windows Chocolatey repositor package. I would need, however, Windows build that provides oracle support.

**Comment by kenshaw** [comment]
I was able to get to get out a homebrew formula, which you can now use with homebrew:
```sh
# add the xo tap
$ brew tap xo/xo

# install regular usql with "most" drivers (all drivers excluding oracle and odbc)
$ brew install usql

# install usql with odbc and oracle drivers
$ brew install usql --with-oracle --with-odbc
```
