### ISSUE TITLE
Cannot to connect to local Postgres (ssl required)

### ISSUE THREAD

**Issue by okbob** [knq/usql#13]
<pre>
[pavel@localhost ~]$ ./usql pg://pavel@localhost/template1
Type "help" for help.

pg:pavel@localhost/template1=> select 10;
error: pq: SSL is not enabled on the server
</pre>

**Comment by kenshaw** [comment]
You need too pass the `?sslmode=disable` option in the URL:
```sh
./usql 'pg://pavel@localhost/template1?sslmode=disable'
```
