### ISSUE TITLE
Add support for mssql instances.

### ISSUE THREAD

**Issue by Ivan-Viktorov** [knq/usql#14]
Mssql can have multiple instances on one server. In that case every instance waiting for connections on its own port and you can determine port you need via 1434/udp port.

"github.com/denisenkom/go-mssqldb" driver support this feature, but when i try
usql "ms://user:pass@mssql-server\INSTANCENAME/dbname"
I got error: could not connect to database: parse ms://user:pass@mssql-server\INSTANCENAME: invalid character "\\\\" in host name.

**Comment by kenshaw** [comment]
I just pushed a change to `dburl` which is the related package used by `xo` and `usql` to parse database URLs. Unfortunately, the Sql Server Browser is not supported by the Linux version of SQL Server, and so I cannot test this easily, as I don't have SQL Server installed anymore on a VM to test with.

If you built this from source, you can simply do:
```sh
go get -u github.com/knq/dburl
```

And then:
```sh
go install github.com/knq/usql
```

(or `go build` or whatever)

Please test this, and let me know if this fixes the issue. The syntax I chose for the URLs is the following:

```
sqlserver://user:pass@host:port/instance/dbname
```
Where the `/instance` portion is optional. If you could try this locally, I'd greatly appreciate it. I'm getting `usql` into a point where I will also include vendored versions of the few dependencies used (which includes `dburl`), so I'd like to test this. Your feedback would be greatly appreciated!

**Comment by kenshaw** [comment]
Also, for anyone else coming across this issue, please see this page for documentation on what URLs work with `dburl` (and subsequently `usql`): https://github.com/knq/dburl

**Comment by Ivan-Viktorov** [comment]
Thanks!

Looks like everything works good.
