### ISSUE TITLE
Add support for interactive password input.

### ISSUE THREAD

**Issue by Ivan-Viktorov** [knq/usql#15]
Some passwords may contain ':', '@', '/' and other special characters. Also, passwords in url may cause secure issues.

It would be nice to have an option like -W in psql to input passwords interactively.

**Comment by kenshaw** [comment]
It's on my list to do.

**Comment by kenshaw** [comment]
This will be coming very soon. And roughly support for 90% of all the `psql` command line options. Bear with me.

**Comment by kenshaw** [comment]
Btw, the initial support for this has been committed.
