### ISSUE TITLE
Using usql as a library

### ISSUE THREAD

**Issue by jaxxstorm** [knq/usql#16]
First of all, props on an amazing project!

I'd like to utilize some of the awesome here in my own golang app. The idea is that I could wrap around usql and utilize it to drop me into a sql prompt.

Is this possible, short of shelling out to the usql binary? Which functions/methods could I use?

**Comment by kenshaw** [comment]
There's not a whole lot of logic in `usql` that is specific to it. It uses [`chzyer/readline`](https://github.com/chzyer/readline) for doing the "readline" stuff. `usql` isn't much different (yet) from their multiline example. 

I'm in the middle of making `usql` much more modular in general, and will try to make it reusable by other packages, but it's not at that state yet.

**Comment by kenshaw** [comment]
Please check out the latest version of `usql`, specifically the `usql/handler` package. It's not 100% modular yet, but I will in the next week or so refactor all the actual SQL stuff out of that package completely.

**Comment by jaxxstorm** [comment]
Amazing turnaround! thanks!

**Comment by kenshaw** [comment]
Well, the work on this revision had been in process for the last few days. Have been trying to make it do "some parsing" to better execute queries / behave more like `psql`. Not 100% there yet, but much much closer now.
