### ISSUE TITLE
help suggest \h for SQL help, but it is an invalid command

### ISSUE THREAD

**Issue by jgomo3** [knq/usql#19]
Look:
```
pg:...=> help
You are using usql, the universal command-line interface for SQL databases.
Type:  \copyright for distribution terms
       \h for help with SQL commands
       \? for help with usql commands
       \g or terminate with semicolon to execute query
       \q to quit
pg:...=> \h
Invalid command \h. Try \? for help.
pg:...=>  
```

**Comment by kenshaw** [comment]
Yes -- I'm aware, haven't gotten to implementing the "informational" backslash commands yet to be compatible with `psql`. That's partly because it's a lot of work, and doesn't really add "core functionality" to the actual app. I'll make a point to comment out that bit for now though.

**Comment by jgomo3** [comment]
What about simply removing that line with the `\h` in the help message?

```
pg:...=> help
You are using usql, the universal command-line interface for SQL databases.
Type:  \copyright for distribution terms
       \? for help with usql commands
       \g or terminate with semicolon to execute query
       \q to quit
pg:...=> 
```

**Comment by pbkdf3** [comment]
Came to suggest the same thing as jgomo3, surprised this issue is closed.  It makes for a poor user experience which lowers one's overall confidence in the tool - and this is a tool you want to be able to rely on.
