### ISSUE TITLE
odbc text driver issues

### ISSUE THREAD

**Issue by joebo** [knq/usql#24]
I'm having trouble getting an ODBC text driver to work:

usql "odbc://Microsoft+Text+Driver+(*.txt+*.csv)/?Dbq=c:/temp"
error: adodb: Exception occurred. ([Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified)

usql "odbc://Microsoft+Access+Text+Driver+(*.txt,+*.csv)/?Dbq=c:/temp"
error: adodb: Exception occurred. ([Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified)

From: https://www.connectionstrings.com/microsoft-text-odbc-driver/

Any assistance would be greatly appreciated

**Comment by kenshaw** [comment]
ODBC connection strings are a bit tricky. Please also note that it doesn't appear you are using the actual ODBC driver, but the ADODB/OLE based ODBC driver. You need to build your version using `-tags odbc` to use the actual, "real" ODBC driver (also I can surmise you are on Windows... based on the info above).

So, couple notes:
1. I haven't tried the Microsoft Access driver with ODBC, however it would work. The syntax for the DSN would actually be like this:
```sh
$ usql 'odbc+Microsoft+Access+Text+Driver+(.txt,+.csv):///?Dbq=c:\temp'
```
2. You might want to try the Microsoft ACE driver instead, which works great with CSVs:
```sh
$ usql adodb://Microsoft.ACE.OLEDB.12.0/?Extended+Properties=%22Text%3BHDR=NO%3BFMT=Delimited%22
```
3. I had been meaning to provide my own CSV driver, based on SQLite, but just haven't had the opportunity to implement it yet. Look for that relatively soon, in a future release.
4. If you cannot get the ODBC driver to work directly, you can just use the `\c driver params` backslash command to connect by passing the exact driver parameters to the underlying ODBC driver:
```sh
$ usql
(not connected)=> \c odbc Driver={Microsoft Text Driver (*.txt; *.csv)};Dbq=c:\txtFilesFolder\;
Extensions=asc,csv,tab,txt;
```
Please note that [this driver](https://github.com/alexbrainman/odbc) is used in `usql`, so please refer to its documentation for specifics on specifying connections strings. I don't have a Windows system to test just now, but I will make a point to try to test this to see if it works properly.

**Comment by joebo** [comment]
Thanks for the reply, looking forward to the CSV driver that is part of usql

I didn't have any luck with the Microsoft Text Driver - (may be a 32bit vs 64bit thing)

The Microsoft.ACE.OLEDB.12.0 seems to work
