### ISSUE TITLE
Can't get oracle to work?

### ISSUE THREAD

**Issue by dwendt** [knq/usql#26]
nevermind, looks like golang errors fucking silently when package dependencies fail to install? god that's terrible.

find the broken shit dependencies after you run `go get -u -tags oracle github.com/knq/usql`:
`go list -json ... | grep "Err"`

failed dependencies and their fixes:
`github.com/alexbrainman/odbc`
```
apt install unixodbc unixodbc-dev
```

**Comment by kenshaw** [comment]
The issue was probably with the cgo build. Also, my experience on Windows is that when a build fails, the executable isn't automatically removed. I've never had problems with errors on OSX/Linux.
