### ISSUE TITLE
Can I enable transaction by default? 

### ISSUE THREAD

**Issue by wushilin** [knq/usql#30]
Very scared of accidentally deleting wrong data

Henplus has rc file to set not to auto commit, hope this does as well.

**Comment by kenshaw** [comment]
Yes/no. `usql` is just the client -- depending on the database, there might be an option for underlying Go components to force transactions. For batch modes (ie, using `usql` inside a script, there is the `--single-transaction` command line option that will force any SQL queries to be executed in a single block. There is also the `.usqlrc` file which will execute a command any time you start `usql` from the command line. You could at the beginning of this file put in whatever relevant "`START TRANSACTION;`" command for the database you are using at the beginning of that file.

**Comment by wushilin** [comment]
Thanks. I was hoping to use this in interactive mode, whatever I do, by default don't commit immediately unless I run "commit" command.

The usqlrc file sounds like a viable solution to me. Let me give it a try ! Just to clarify, after I commit, the START TRANSACTION is still in effect right? I mean after my commit, my next update/insert/delete still needs to be explicitly committed right?

Thanks
Best Regards
Shilin
