### ISSUE TITLE
Provide executable for platforms

### ISSUE THREAD

**Issue by modulexcite** [knq/usql#4]
Hi,

Thank you for an excellent tool and sharing with the community, would you be open to providing an executable for windows and other platforms. I would like to use it without having to install the `Go` language on the host.

**Comment by kenshaw** [comment]
Yes -- this will be done. Please bear with me as usql is only about 1.5 days old now.

**Comment by modulexcite** [comment]
Absolutely, thought I'd check.You :metal:

**Comment by kenshaw** [comment]
Binary releases are being put up now.

**Comment by modulexcite** [comment]
Awesome, thank you.
