### ISSUE TITLE
Dependency Manager

### ISSUE THREAD

**Issue by avelino** [knq/usql#5]
Why not use a dependency Manager? It can help to have future problems of update packages that you use.

- godep (https://github.com/tools/godep)

**Comment by kenshaw** [comment]
I will likely vendor the dependencies, as this is a command line tool. Please bear with me, as this is project is only about 1.5 days old. But I am planning on making this a real, world-class tool, meaning that it has all the standard kinds of things such as dependencies / releases / etc.
