### ISSUE TITLE
Allow Postgres without SSL?

### ISSUE THREAD

**Issue by prashnts** [knq/usql#6]
In my local dev setup, SSL is not enabled in PG. It throws this error, in this case:
```
usql pg://localhost/agoranhs
Type "help" for help.

pg:localhost/agoranhs=> select * from events limit 2;
error: pq: SSL is not enabled on the server
pg:localhost/agoranhs=> ^D
```

**Comment by kenshaw** [comment]
You need to pass the 'sslmode=disable' in the URL:

```sh
usql 'postgres://localhost/dbname?sslmode=disable'
```

This is due to the way that the `lib/pq` PostgreSQL driver handles SSL connections. Please see here: https://github.com/lib/pq

**Comment by berdon** [comment]
Can we add this to the readme.md? Otherwise this is pretty lost to newcomers.

**Comment by eadmaster** [comment]
another way to handle this would be appending an `s` in the protocol name (e.g. `pgs`)

**Comment by kid1412621** [comment]
> You need to pass the 'sslmode=disable' in the URL:
> 
> ```shell
> usql 'postgres://localhost/dbname?sslmode=disable'
> ```
> 
> This is due to the way that the `lib/pq` PostgreSQL driver handles SSL connections. Please see here: https://github.com/lib/pq

is there anyway to disable it by default?
