### ISSUE TITLE
go-get on Mac does install usql

### ISSUE THREAD

**Issue by meet-bhagdev** [knq/usql#7]
I did the following:

```
go get -u github.com/knq/usql
usql --help #returns command not found
```

**Comment by kenshaw** [comment]
You need a Go build toolchain installed. I will be releasing binaries, but am backlogged at the moment as this project is only about 1.5 days old.

**Comment by meet-bhagdev** [comment]
ok sounds good! I installed GO from here: https://golang.org/doc/install?download=go1.8.darwin-amd64.pkg

How do I install the tool chain?

**Comment by chischaschos** [comment]
This is what I did:

1. Install go with brew:
   `brew install go`
2. Set a `GOPATH` in your .zshrc or .profile or .bashrc (depending on your shell), in my case my .zshrc:
  ```
  mkdir ~/Projects/GOPATH
  export GOPATH=~/Projects/GOPATH
  ```
3. Add the `go` built binaries to your path:
  ```
  PATH="$HOME/usr/local/bin:$GOPATH/bin:$PATH"
  export -U PATH
  ```

Hope that help!!!

**Comment by kenshaw** [comment]
There are binary releases now, [available here](https://github.com/knq/usql/releases).
