### ISSUE TITLE
Can I ask you a favor?

### ISSUE THREAD

**Issue by MikeRys** [knq/usql#9]
Hi Ken

I am the Program Manager in the Microsoft Big Data Team who manages the U-SQL Language project.

I have noticed that you are using the name usql for a cool project providing a unified SQL command line tool. 

Unfortunately, we have a SQL like language called U-SQL (often hashtagged with #USQL since twitter cannot handle – in references) for which we have a trademark. Both these names are in the same general space, and based on the comments on hacker news, it seems that it can lead to confusion (besides the search collisions on GitHub). 

Can I kindly ask you to change the name of your project? If you do, I am more than happy to help with spreading the news about the tool and its new name on my blog and twitter account.

Thanks 
Michael

**Comment by kenshaw** [comment]
Hi Michael,

Thanks for the input. Unfortunately, I did not know about the U-SQL project when I sat down to initially write `usql`, however when I read the comment in the Hacker News comment, I made immediate plans to add support for working with U-SQL (and any and in fact, any and all related SQL languages).

As a matter of fact, it already works quite well with Microsoft SQL server on Linux. I don't imagine it would require much finessing to work with Azure. As I definitely plan on making U-SQL a central part of the `usql` cli, I can't imagine it would be a problem for what the fine people at Microsoft are doing.

Also of note, that the 'u' in `usql` does not stand for 'unified', but instead is representative of the Greek letter mu.

PS: if you had wanted to contact me directly, and not here in a public forum, my email is available on my profile and in the commit history. Thanks!

**Comment by kenshaw** [comment]
Hi Michael,

I'd also like to point out these other projects that are named 'usql' or some variation thereof: https://github.com/search?utf8=%E2%9C%93&q=usql

Many of them predate Microsoft's trademark registration, and appear to be SQL related. Additionally, there are other projects on Sourceforge named 'usql', including one that is over a decade old, and has the exact goal as this project, however it does not appear to be maintained.

I'm curious, have you contacted them and asked them to change their project names?

**Comment by MikeRys** [comment]
Thanks Ken. your email does not show on your profile nor the commit history (feel free to reply to mrys at Microsoft dot com). I have not yet contacted the other projects, primarily because they either call out explicitly that they are using the u as a "mu" or their projects look dead/classroom related (there is no twitter activity for example :)). I may contact some of the others as well. 

Could you maybe call it musql instead or use the Greek character directly? That would definitively help with the trademark issues and the possible confusions.

Thanks
Michael
